### ISSUE TITLE
'Window does not have a parent' error in @contentstack/app-sdk

### ISSUE THREAD

**Issue by sxurik** [contentstack/app-sdk-docs#4]
The problem is with [@contentstack/app-sdk](https://www.npmjs.com/package/@contentstack/app-sdk) itself, but [github.com/contentstack/app-sdk/](https://github.com/contentstack/app-sdk/) is 404 for me, so I'll create an issue here.
I hope, it's all right.

I'm trying to create a custom application as described [here](https://www.contentstack.com/docs/developers/developer-hub/get-started-with-building-apps-using-contentstack-app-sdk/), [here](https://www.contentstack.com/docs/developers/developer-hub/guide-to-build-your-first-simple-app/) and [here](https://www.contentstack.com/docs/developers/developer-hub/marketplace-app-boilerplate/).
I downloaded an app boilerplate from [this link](https://assets.contentstack.io/v3/assets/blt23180bf2502c7444/blta553fcb6194cbca6/627e0cb6dcc93261ecca4f9e/app-boilerplate-1.zip?disposition=download) and I'm following steps in the guides. 

But the first call to the sdk - `ContentstackAppSdk.init()` results in this error:

![image](https://user-images.githubusercontent.com/32016927/191008191-b6578780-ad28-4527-a8b5-3aa9a4ff94d8.png)

![image](https://user-images.githubusercontent.com/32016927/191008225-cab0a47e-e14b-4053-a22e-f53b96a6b9f3.png)

Am I missing some set-up steps, maybe? Or is it an issue with the sdk?

Thanks in advance for your help.

**Comment by Deepak-Kharah** [comment]
Hey @sxurik, the plugins created using the app-sdk are meant to be run by Contentstack. Contentstack run these plugins inside an iframe; hence it expects a parent. If you run this app inside Contentstack, the app will not throw this error. 

I am closing this issue-- please reopen it if that didn't work or if you have any other questions. Thanks.

**Comment by sxurik** [comment]
We've already figured it out. No need to reopen the issue.

Just some suggestions, that can prevent other people from wasting their time on the error message:

1. Having a note like "Contentstack run these plugins inside an iframe; hence it expects a parent" in the [docs for App SDK](https://github.com/contentstack/app-sdk-docs).
2. Making source code for the App SDK public (seems like it used to be, but right now it's 404 - https://github.com/contentstack/app-sdk/).
3. Adding this information at least somewhere (see the links in the description of the issue).

**Comment by Deepak-Kharah** [comment]
Noted, we'll add this information somewhere in the documentation.
